basePath: /
definitions:
  models.Todo:
    properties:
      body:
        type: string
      completed:
        type: boolean
      id:
        type: integer
    type: object
host: localhost:8080
info:
  contact: {}
  description: A simple todo list REST API.
  title: Todo List API
  version: "1.0"
paths:
  /todos:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Todo'
            type: array
      summary: List all todos
      tags:
      - todos
    post:
      consumes:
      - application/json
      parameters:
      - description: Todo body
        in: body
        name: todo
        required: true
        schema:
          $ref: '#/definitions/models.Todo'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Todo'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create a todo
      tags:
      - todos
swagger: "2.0"
